### ISSUE TITLE
'change output path or enable force_overwrite setting'

### ISSUE THREAD

**Issue by jonnyhtw** [dionhaefner/veros#34]
Hi there, me again!

Could you please let me know how to run with the `force_overwrite` setting? I can't seem to work it out!

Thanks

Jonny

**Comment by dionhaefner** [comment]
Easy: either add the following to the `set_parameter` method of your setup

```python
self.force_overwrite = True
```

or invoke your setup with

```bash
python mysetup.py -s force_overwrite True
```

(the `-s` flag overrides settings from the command line)

**Comment by dionhaefner** [comment]
By the way, all available settings are documented here:

http://veros.readthedocs.io/reference/settings.html

**Comment by jonnyhtw** [comment]
OK that's super, thanks a lot. I did look in the docs but clearly not hard enough!

Cheers

Jonny

**Comment by dionhaefner** [comment]
Happy to help.
