### ISSUE TITLE
inconsistent licence

### ISSUE THREAD

**Issue by mvhulten** [dionhaefner/veros#41]
The licence stated in the [discussion paper](https://doi.org/10.5194/gmd-2018-3) is GPL.  The licence file in the repository is MIT.  If you want the code for instance to be licensed under GPL>=3.0, the LICENSE file should be replaced, and it is best to be precise in the paper, e.g. "... code is available under the GNU General Public License version 3.0, or, at your option, any higher version."

By the way, it is fantastic that this code is developed and shared (as free software)—an important contribution to ocean modelling and oceanography!

**Comment by dionhaefner** [comment]
I chose to re-license Veros under MIT from v0.1.1 onward. v0.1.0, the version described in the paper, was licensed under GPL. I agree that I should have been more precise in the paper, thanks for pointing that out.

**Comment by mvhulten** [comment]
Ah yes, I see!  That will be a simple change in the paper then (assuming the final paper will describe Veros>=v0.1.1).

I just learnt something about the [naming](https://www.gnu.org/licenses/license-list.html#X11License) of the X11/MIT licence.  You can of course decide if it is important enough.  Most important considering the distribution, in my opinion, is that the program is free software, and second most important that it is GPL *compatible*.
