### ISSUE TITLE
RuntimeError: Two parallel Veros+Bohrium runs on two GPUs on the same node

### ISSUE THREAD

**Issue by nutrik** [dionhaefner/veros#43]
Hi Dion,

It seems impossible to make 2 parallel/standalone Veros runs on 2 GPUs on the same node. The error message is below. Is it something to do with OpenCL keys?
Do you think that should work if I would have two separate versions of veros and/or bohrium and use them for individual runs?

```
Time step took 4.14e+00s
Current iteration: 17
build program: binary cache hit (key: 219cf206d832af2614aabaa6095b2a6d)
build program: start
build program: completed, success
pyopencl-invoker-cache-v1: in mem cache hit [key=1fc007e39493fed6f5e0c45672144578c269a48fd12e4bc28dc2ce3b7c1dc753]
build program: binary cache hit (key: 219cf206d832af2614aabaa6095b2a6d)
build program: start
build program: completed, success
pyopencl-invoker-cache-v1: in mem cache hit [key=1fc007e39493fed6f5e0c45672144578c269a48fd12e4bc28dc2ce3b7c1dc753]
Error code: -4
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueNDRangeKernel
Traceback (most recent call last):
  File "/groups/ocean/software/veros/inst06032018/bin/veros-resubmit", line 11, in <module>
    load_entry_point('veros', 'console_scripts', 'veros-resubmit')()
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo06032018/veros/cli/veros_resubmit.py", line 81, in cli
    resubmit(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo06032018/veros/cli/veros_resubmit.py", line 61, in resubmit
    call_veros(veros_cmd, identifier, current_n, length_per_run)
  File "/lustre/hpc/ocean/software/veros/repo06032018/veros/cli/veros_resubmit.py", line 46, in call_veros
    raise RuntimeError("Run {} failed, exiting".format(n))
RuntimeError: Run 0 failed, exiting
```

**Comment by dionhaefner** [comment]
What kind of environment variables did you use? 

You need to tell Bohrium which GPU you want to use; that should be possible via `BH_OPENCL_PLATFORM_NO` (see [docs](http://bohrium.readthedocs.io/users/config.html#opencl-configuration)). Trying to run both instances on the same GPU fails because the device runs out of memory.

**Comment by nutrik** [comment]
List of environment variables related to bohrium:
```
export BH_STACK=opencl
export BH_OPENCL_DEVICE_TYPE=gpu
export BH_OPENCL_PLATFORM_NO=0

module load bohrium/06032018
module load veros/06032018
```

I tried numbers 0 and 1 for `BH_OPENCL_PLATFORM_NO` variable, but there is only 0 available.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No such OpenCL platform. Tried to fetch #1 out of 0.
```

**Comment by dionhaefner** [comment]
Interesting. Bohrium actually only offers an option to choose the OpenCL *platform* (such as CPU vs. GPU), not the *device* on that platform to be used for computations (is seems to choose the first it finds: https://github.com/bh107/bohrium/blob/9f022432ead25bfccb68a13d8fa032b638d7b6bf/ve/opencl/engine_opencl.cpp#L62). You should raise this issue with Bohrium. Up until then, I'm afraid it's not possible to run Veros on multiple devices on the same platform in parallel.

**Comment by omegahm** [comment]
With https://github.com/bh107/bohrium/pull/526 having been merged to master on the Bohrium project, you should be able to choose the different GPUs with `BH_OPENCL_DEVICE_NUMBER=0` and `BH_OPENCL_DEVICE_NUMBER=1`.
